set -g default-terminal "screen-256color"

# Change prefix to Ctrl+space.
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

bind r source-file ~/.tmux.conf \; display "Config reloaded!"

bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5

bind -r m resize-pane -Z

set -g mouse on

set-window-option -g mode-keys vi

# Automatically reset window numbers whenever a window is closed.
# Ensures window indices remain sequential and gapless.
set -g renumber-windows on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin "janoamaral/tokyo-night-tmux"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'   
